### Create all messages
POST http://localhost:3000/auth/signup
content-type: application/json

{
	"email"	: "a@a.com",
	"password"	: "passwoord"
}

### Get a User
GET http://localhost:3000/auth/3

### Find All Users with a given email
GET http://localhost:3000/auth?email=c@c.com

### Delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
DELETE http://localhost:3000/auth/2
content-type: application/json

{
	"email"	: "c@c.com"
}